language: python
python:
  - "2.7"
  - "3.2"
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -qq python3-numpy python3-scipy
install:
  - pip install coveralls
  - pip install pep8
script:
  - pep8 hypergraph
  - coverage run --source=hypergraph setup.py test
after_success:
    coveralls
