language: python

python:
  - 2.7
  - 3.2

virtualenv:
    system_site_packages: true

install:
  - pip install coveralls
  - pip install pep8
  - pip install networkx
  # need the following installed from their respective github repos
  # to ensure that the latest version of numpy and scipy are installed;
  # causes errors in the TravisCI framework otherwise
  # downside: TravisCI now takes ~20-25 minutes to finish its run
  - sudo apt-get install libatlas-base-dev gfortran
  - pip install git+http://github.com/cython/cython/
  - pip install git+http://github.com/numpy/numpy/
  - pip install git+http://github.com/scipy/scipy/

script:
  - pep8 halp
  - coverage run --source=halp setup.py test

after_success:
    coveralls
