language: python

python:
  - 2.7
  - 3.2

virtualenv:
    system_site_packages: true

before-install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy python-scipy
  - sudo apt-get install -qq python3-numpy python3-scipy

install:
  - pip install coveralls
  - pip install pep8
  - sudo apt-get install libatlas-base-dev gfortran
  - pip install git+http://github.com/cython/cython/
  - pip install git+http://github.com/numpy/numpy/
  - pip install git+http://github.com/scipy/scipy/

script:
  - pep8 hypergraph
  - coverage run --source=hypergraph setup.py test

after_success:
    coveralls
